import pandas as pd
import os
import re
from datetime import datetime
from collections import defaultdict

# --------------------------------------------------
# CONFIG
# --------------------------------------------------

# Current file:
# WatsonInstitute/python-scripts/optimized/script.py
#
# We go UP 3 folders to reach:
# WatsonInstitute/

BASE_DIR = os.path.dirname(
    os.path.dirname(
        os.path.dirname(os.path.abspath(__file__))
    )
)

reports_folder = os.path.join(
    BASE_DIR,
    "reports"
)

email_col = "Email (Enter Email)"
progress_col = "Progress"
entry_date_col = "Entry Date"

# Name shown in the exported Excel ONLY.
# Internally the script keeps using "Entry Date" (the Gravity Forms name).
entry_date_display = "Date Updated"

original_entry_col = "Original-Entry-Date"
days_partial_col = "Days-as-Partial-Entry"

# Columnas cuyo título debe verse completo (sin recortar)
# en todas las pestañas donde aparezcan
full_header_cols = {
    "In what state does your organization or business primarily create impact?"
}


# --------------------------------------------------
# COLUMN ORDER FOR THE DATE COLUMNS
# --------------------------------------------------
#
# Desired order:
#   Original-Entry-Date, Save and Continue URL, Date Updated
#
# The three columns swap places among the positions they already
# occupy, so every other column stays exactly where it is.
#
# --------------------------------------------------

def reorder_date_columns(df):

    desired = [
        original_entry_col,
        "Save and Continue URL",
        entry_date_display
    ]

    present = [
        c for c in desired
        if c in df.columns
    ]

    if len(present) < 2:
        return df

    cols = df.columns.tolist()

    slots = sorted(
        cols.index(c) for c in present
    )

    for slot, col in zip(slots, present):

        cols[slot] = col

    return df[cols]


# --------------------------------------------------
# VALIDATE REPORTS FOLDER
# --------------------------------------------------

if not os.path.exists(reports_folder):

    print("\nERROR:")
    print(f"Reports folder not found:\n{reports_folder}")

    raise FileNotFoundError(
        f"Missing folder: {reports_folder}"
    )


# --------------------------------------------------
# FIND ALL REPORT FILES
# --------------------------------------------------

program_files = defaultdict(list)

# Weekly files generated by this script (they hold Original-Entry-Date)
weekly_outputs = defaultdict(list)

for root, dirs, files in os.walk(reports_folder):

    for file in files:

        # Previously generated "- Weekly.xlsx" outputs

        if (
            file.endswith(" - Weekly.xlsx")
            and "Partial Entries Report" in file
        ):

            weekly_match = re.match(
                r"(\d{2}-\d{2}-\d{4}) - (.+?) - Partial Entries Report",
                file
            )

            if weekly_match:

                try:

                    weekly_outputs[
                        weekly_match.group(2).strip()
                    ].append(
                        (
                            datetime.strptime(
                                weekly_match.group(1),
                                "%m-%d-%Y"
                            ),
                            os.path.join(root, file)
                        )
                    )

                except Exception:
                    pass

            continue


        if (
            file.endswith(".xlsx")
            and "Partial Entries Report" in file
            and "Weekly" not in file
        ):

            match = re.match(
                r"(\d{2}-\d{2}-\d{4}) - (.+?) - Partial Entries Report",
                file
            )

            if not match:
                continue

            try:

                report_date = datetime.strptime(
                    match.group(1),
                    "%m-%d-%Y"
                )

                program_name = match.group(2).strip()

                full_path = os.path.join(
                    root,
                    file
                )

                program_files[program_name].append(
                    (report_date, full_path)
                )

            except Exception:
                pass


# --------------------------------------------------
# PROCESS EACH PROGRAM
# --------------------------------------------------

for program, files in program_files.items():

    if len(files) < 2:
        continue

    # --------------------------------------------------
    # SORT FILES
    # --------------------------------------------------

    files.sort(key=lambda x: x[0])

    previous_date, previous_file = files[-2]

    latest_date, latest_file = files[-1]

    latest_filename = os.path.basename(
        latest_file
    )


    # --------------------------------------------------
    # LOAD FINAL SHEETS
    # --------------------------------------------------

    try:

        df_previous = pd.read_excel(
            previous_file,
            sheet_name="Final"
        )

        df_latest = pd.read_excel(
            latest_file,
            sheet_name="Final"
        )

    except Exception as e:

        print(
            f"\nERROR reading Final sheets: {e}"
        )

        continue


    # --------------------------------------------------
    # CLEAN COLUMN NAMES
    # --------------------------------------------------

    df_previous.columns = (
        df_previous.columns
        .astype(str)
        .str.strip()
    )

    df_latest.columns = (
        df_latest.columns
        .astype(str)
        .str.strip()
    )


    # --------------------------------------------------
    # VALIDATE EMAIL COLUMN
    # --------------------------------------------------

    if email_col not in df_previous.columns:

        print(
            "\nMissing email column in previous file."
        )

        continue

    if email_col not in df_latest.columns:

        print(
            "\nMissing email column in latest file."
        )

        continue


    # --------------------------------------------------
    # NORMALIZE EMAILS
    # --------------------------------------------------

    df_previous[email_col] = (
        df_previous[email_col]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    df_latest[email_col] = (
        df_latest[email_col]
        .astype(str)
        .str.strip()
        .str.lower()
    )


    # --------------------------------------------------
    # NORMALIZE ENTRY DATES
    # --------------------------------------------------

    if entry_date_col in df_previous.columns:

        df_previous[entry_date_col] = pd.to_datetime(
            df_previous[entry_date_col],
            errors="coerce"
        )

    else:

        df_previous[entry_date_col] = pd.NaT


    if entry_date_col in df_latest.columns:

        df_latest[entry_date_col] = pd.to_datetime(
            df_latest[entry_date_col],
            errors="coerce"
        )

    else:

        df_latest[entry_date_col] = pd.NaT


    # --------------------------------------------------
    # BUILD HISTORICAL ORIGINAL DATE LOOKUP
    # --------------------------------------------------
    #
    # For every email in the previous report:
    #
    # 1. Use Original-Entry-Date if it exists.
    # 2. Also consider the previous Entry Date.
    # 3. Keep the OLDEST date available.
    #
    # This allows the system to continue working even
    # when the previous report was created before the
    # Original-Entry-Date column existed.
    #
    # --------------------------------------------------

    previous_original_dates = {}


    for _, row in df_previous.iterrows():

        email = row[email_col]

        if pd.isna(email):
            continue

        dates = []


        # Existing historical original date

        if original_entry_col in df_previous.columns:

            historical_date = pd.to_datetime(
                row[original_entry_col],
                errors="coerce"
            )

            if pd.notna(historical_date):

                dates.append(
                    historical_date
                )


        # Previous Entry Date

        previous_entry_date = row[
            entry_date_col
        ]

        if pd.notna(previous_entry_date):

            dates.append(
                previous_entry_date
            )


        # Keep oldest known date

        if dates:

            oldest_date = min(dates)

            if (
                email not in previous_original_dates
                or oldest_date
                < previous_original_dates[email]
            ):

                previous_original_dates[email] = (
                    oldest_date
                )


    # --------------------------------------------------
    # CARRY FORWARD ORIGINAL DATES FROM PREVIOUS WEEKLY OUTPUT
    # --------------------------------------------------
    #
    # The raw previous report does NOT contain Original-Entry-Date,
    # but the "- Weekly.xlsx" file generated by this script does
    # (Final tab). We use the most recent Weekly file that is older
    # than the latest report and merge its dates, always keeping
    # the OLDEST date per email.
    #
    # --------------------------------------------------

    earlier_weekly = [
        item
        for item in weekly_outputs.get(program, [])
        if item[0] < latest_date
    ]

    if earlier_weekly:

        earlier_weekly.sort(key=lambda x: x[0])

        weekly_prev_date, weekly_prev_file = earlier_weekly[-1]

        try:

            df_weekly_prev = pd.read_excel(
                weekly_prev_file,
                sheet_name="Final"
            )

            df_weekly_prev.columns = (
                df_weekly_prev.columns
                .astype(str)
                .str.strip()
            )

            if (
                email_col in df_weekly_prev.columns
                and original_entry_col in df_weekly_prev.columns
            ):

                weekly_emails = (
                    df_weekly_prev[email_col]
                    .astype(str)
                    .str.strip()
                    .str.lower()
                )

                weekly_originals = pd.to_datetime(
                    df_weekly_prev[original_entry_col],
                    errors="coerce"
                )

                for email, original_date in zip(
                    weekly_emails,
                    weekly_originals
                ):

                    if pd.isna(original_date):
                        continue

                    if (
                        email not in previous_original_dates
                        or original_date
                        < previous_original_dates[email]
                    ):

                        previous_original_dates[email] = (
                            original_date
                        )

        except Exception as e:

            print(
                f"\nWARNING [{program}]: could not read "
                f"previous Weekly file: {e}"
            )


    # --------------------------------------------------
    # BUILD ORIGINAL-ENTRY-DATE FOR LATEST REPORT
    # --------------------------------------------------
    #
    # The original date is the oldest known date between:
    #
    # - Current Entry Date
    # - Current Original-Entry-Date, if available
    # - Previous historical Original-Entry-Date
    # - Previous Entry Date
    #
    # --------------------------------------------------

    original_dates = []


    for _, row in df_latest.iterrows():

        email = row[email_col]

        dates = []


        # Current Entry Date

        current_entry_date = row[
            entry_date_col
        ]

        if pd.notna(current_entry_date):

            dates.append(
                current_entry_date
            )


        # Current Original-Entry-Date
        # (useful if this column already exists
        # for any reason)

        if original_entry_col in df_latest.columns:

            current_original_date = pd.to_datetime(
                row[original_entry_col],
                errors="coerce"
            )

            if pd.notna(current_original_date):

                dates.append(
                    current_original_date
                )


        # Historical date from previous report

        previous_original_date = (
            previous_original_dates.get(
                email
            )
        )

        if pd.notna(previous_original_date):

            dates.append(
                previous_original_date
            )


        # Select oldest known date

        if dates:

            original_dates.append(
                min(dates)
            )

        else:

            original_dates.append(
                pd.NaT
            )


    # Add / replace Original-Entry-Date

    df_latest[original_entry_col] = (
        original_dates
    )


    # --------------------------------------------------
    # CALCULATE DAYS-AS-PARTIAL-ENTRY
    # --------------------------------------------------
    #
    # Number of days from the original entry date
    # until the date of the latest report.
    #
    # Example:
    #
    # Original: 09-21-2026
    # Report:   09-28-2026
    #
    # Result: 7
    #
    # A new entry on 09-28:
    #
    # Original: 09-28-2026
    # Report:   09-28-2026
    #
    # Result: 0
    #
    # --------------------------------------------------

    report_date = pd.Timestamp(
        latest_date
    ).normalize()


    df_latest[days_partial_col] = (
        report_date
        - pd.to_datetime(
            df_latest[original_entry_col],
            errors="coerce"
        ).dt.normalize()
    ).dt.days


    # Prevent unexpected negative values

    df_latest[days_partial_col] = (
        df_latest[days_partial_col]
        .where(
            df_latest[days_partial_col] >= 0,
            0
        )
    )


    # --------------------------------------------------
    # FIND NEW ENTRIES
    # --------------------------------------------------

    previous_emails = set(
        df_previous[email_col]
    )

    weekly_new = df_latest[
        ~df_latest[email_col].isin(
            previous_emails
        )
    ].copy()


    # --------------------------------------------------
    # SAVE AND CONTINUE URL WEEKLY
    # --------------------------------------------------

    save_continue_col = "Save and Continue URL"

    # Valores que NO se consideran un URL válido
    invalid_urls = {
        "?gf_token=undefined"
    }

    if save_continue_col in weekly_new.columns:

        url_series = (
            weekly_new[save_continue_col]
            .fillna("")
            .astype(str)
            .str.strip()
        )

        save_continue_weekly = (
            weekly_new[
                url_series.ne("")
                & ~url_series.str.lower().isin(invalid_urls)
            ]
            .copy()
        )

    else:

        save_continue_weekly = pd.DataFrame()


    # --------------------------------------------------
    # DIAGNOSTIC: URLs con solo token (solo aviso, no modifica nada)
    # --------------------------------------------------

    if save_continue_col in weekly_new.columns:

        diag_series = (
            weekly_new[save_continue_col]
            .fillna("")
            .astype(str)
            .str.strip()
            .str.lower()
        )

        token_only_count = (
            diag_series.str.startswith("?gf_token=")
            & ~diag_series.isin(invalid_urls)
        ).sum()

        if token_only_count > 0:

            print(
                f"\nNOTE [{program}]: {token_only_count} URL(s) "
                f"vienen solo con el token (sin URL completo)."
            )


    # --------------------------------------------------
    # LOAD ORIGINAL SUMMARY
    # --------------------------------------------------

    try:

        original_summary = pd.read_excel(
            latest_file,
            sheet_name="Summary"
        )

    except Exception:

        original_summary = pd.DataFrame(
            columns=[
                "Metric",
                "Count"
            ]
        )


    # --------------------------------------------------
    # BUILD FINAL SUMMARY
    # --------------------------------------------------

    summary_append = pd.DataFrame(
        [
            (
                "New Partial Entries This Week",
                len(weekly_new)
            ),
            (
                "Latest Report",
                latest_filename
            ),
            (
                "Previous Report",
                os.path.basename(
                    previous_file
                )
            )
        ],
        columns=[
            "Metric",
            "Count"
        ]
    )


    summary_df = pd.concat(
        [
            original_summary,
            summary_append
        ],
        ignore_index=True
    )


    # --------------------------------------------------
    # LOAD LOCATION TAB
    # --------------------------------------------------

    location_exists = False

    try:

        location_df = pd.read_excel(
            latest_file,
            sheet_name="Location",
            header=None
        )

        location_exists = True

    except Exception:

        pass


    # --------------------------------------------------
    # OUTPUT FILE
    # --------------------------------------------------

    output_filename = latest_filename.replace(
        ".xlsx",
        " - Weekly.xlsx"
    )

    output_path = os.path.join(
        os.path.dirname(latest_file),
        output_filename
    )


    # --------------------------------------------------
    # DELETE EXISTING FILE
    # --------------------------------------------------

    if os.path.exists(output_path):

        try:

            os.remove(output_path)

        except PermissionError:

            print(
                "\n==================================="
            )

            print(
                "FILE IS OPEN - CLOSE EXCEL FILE"
            )

            print(
                "==================================="
            )

            print(output_path)

            continue


    # --------------------------------------------------
    # RENAME ENTRY DATE COLUMN (OUTPUT ONLY)
    # --------------------------------------------------
    #
    # All the logic above keeps using "Entry Date".
    # The rename happens here, right before writing the Excel,
    # so nothing upstream is affected.
    #
    # --------------------------------------------------

    weekly_new = weekly_new.rename(
        columns={entry_date_col: entry_date_display}
    )

    save_continue_weekly = save_continue_weekly.rename(
        columns={entry_date_col: entry_date_display}
    )

    df_latest = df_latest.rename(
        columns={entry_date_col: entry_date_display}
    )


    # Order: Original-Entry-Date, Save and Continue URL, Date Updated

    weekly_new = reorder_date_columns(weekly_new)

    save_continue_weekly = reorder_date_columns(
        save_continue_weekly
    )

    df_latest = reorder_date_columns(df_latest)


    # --------------------------------------------------
    # EXPORT REPORT
    # --------------------------------------------------

    try:

        with pd.ExcelWriter(
            output_path,
            engine="xlsxwriter"
        ) as writer:

            # --------------------------------------------------
            # 1. WEEKLY
            # --------------------------------------------------

            weekly_new.to_excel(
                writer,
                sheet_name="Weekly",
                index=False
            )


            # --------------------------------------------------
            # 2. SAVE AND CONTINUE URL WEEKLY
            # --------------------------------------------------

            if not save_continue_weekly.empty:

                save_continue_weekly.to_excel(
                    writer,
                    sheet_name=(
                        "Save-and-Continue-URL-weekly"
                    ),
                    index=False
                )


            # --------------------------------------------------
            # 3. FINAL
            # --------------------------------------------------

            df_latest.to_excel(
                writer,
                sheet_name="Final",
                index=False
            )


            # --------------------------------------------------
            # 4. LOCATION
            # --------------------------------------------------

            if location_exists:

                location_df.to_excel(
                    writer,
                    sheet_name="Location",
                    index=False,
                    header=False
                )


            # --------------------------------------------------
            # 5. SUMMARY
            # --------------------------------------------------

            summary_df.to_excel(
                writer,
                sheet_name="Summary",
                index=False
            )


            # ==================================================
            # FORMAT NORMAL SHEETS
            # ==================================================

            sheets = {
                "Weekly": weekly_new,
                "Final": df_latest,
                "Summary": summary_df
            }


            if not save_continue_weekly.empty:

                sheets[
                    "Save-and-Continue-URL-weekly"
                ] = save_continue_weekly


            # Formato de encabezado: azul marino oscuro + letra blanca

            header_format = writer.book.add_format(
                {
                    "bold": True,
                    "font_color": "#FFFFFF",
                    "bg_color": "#1F3864",
                    "border": 1,
                    "border_color": "#FFFFFF",
                    "valign": "vcenter"
                }
            )


            for sheet, dataframe in sheets.items():

                ws = writer.sheets[sheet]

                ws.freeze_panes(
                    1,
                    0
                )


                if len(dataframe.columns) > 0:

                    ws.autofilter(
                        0,
                        0,
                        len(dataframe),
                        len(dataframe.columns) - 1
                    )


                for i, col in enumerate(
                    dataframe.columns
                ):

                    series = (
                        dataframe[col]
                        .fillna("")
                        .astype(str)
                    )

                    if len(series) > 0:

                        max_len = max(
                            series.map(len).max(),
                            len(col)
                        ) + 2

                    else:

                        max_len = (
                            len(col) + 2
                        )


                    if col in full_header_cols:

                        # Ancho suficiente para ver el título completo
                        # (+4 para el botón del autofiltro)
                        col_width = len(col) + 4

                    else:

                        col_width = min(max_len, 50)


                    ws.set_column(
                        i,
                        i,
                        col_width
                    )


                    # Encabezado con formato azul marino / letra blanca

                    ws.write(
                        0,
                        i,
                        col,
                        header_format
                    )


            # ==================================================
            # FORMAT DATE COLUMNS
            # ==================================================

            date_format = writer.book.add_format(
                {
                    "num_format": "mm-dd-yyyy"
                }
            )


            for sheet_name, dataframe in {
                "Weekly": weekly_new,
                "Final": df_latest
            }.items():

                ws = writer.sheets[
                    sheet_name
                ]


                for date_column in [
                    entry_date_display,
                    original_entry_col
                ]:

                    if date_column in dataframe.columns:

                        column_index = (
                            dataframe.columns
                            .get_loc(
                                date_column
                            )
                        )

                        ws.set_column(
                            column_index,
                            column_index,
                            18,
                            date_format
                        )


            # ==================================================
            # FORMAT LOCATION
            # ==================================================

            if location_exists:

                ws_location = writer.sheets[
                    "Location"
                ]

                ws_location.freeze_panes(
                    1,
                    0
                )


                for i in range(
                    location_df.shape[1]
                ):

                    series = (
                        location_df[i]
                        .fillna("")
                        .astype(str)
                    )


                    if len(series) > 0:

                        max_len = (
                            series.map(len).max()
                        ) + 2

                    else:

                        max_len = 10


                    ws_location.set_column(
                        i,
                        i,
                        min(max_len, 40)
                    )


                # ----------------------------------------------
                # LOCATION: encabezado + un filtro por bloque
                # ----------------------------------------------
                #
                # Excel solo permite UN autofiltro por hoja, pero
                # cada tabla de Excel tiene su propio filtro.
                # Por eso cada bloque de columnas contiguas con
                # encabezado (ej. Country y State) se convierte
                # en una tabla independiente, sin estilo propio
                # para conservar el formato azul marino.
                #
                # ----------------------------------------------

                header_row = location_df.iloc[0]

                # Detectar bloques de columnas contiguas con encabezado

                blocks = []
                start = None

                for c in range(location_df.shape[1]):

                    value = header_row.iloc[c]

                    has_header = (
                        pd.notna(value)
                        and str(value).strip() != ""
                    )

                    if has_header and start is None:

                        start = c

                    if not has_header and start is not None:

                        blocks.append((start, c - 1))
                        start = None

                if start is not None:

                    blocks.append(
                        (start, location_df.shape[1] - 1)
                    )


                for n, (c0, c1) in enumerate(blocks, start=1):

                    last_row = (
                        location_df.iloc[:, c0:c1 + 1]
                        .dropna(how="all")
                        .index.max()
                    )

                    # Sin filas de datos: solo dar formato al encabezado

                    if last_row < 1:

                        for c in range(c0, c1 + 1):

                            ws_location.write(
                                0,
                                c,
                                str(header_row.iloc[c]).strip(),
                                header_format
                            )

                        continue


                    ws_location.add_table(
                        0,
                        c0,
                        last_row,
                        c1,
                        {
                            "name": f"Location_Table_{n}",
                            "style": None,
                            "autofilter": True,
                            "columns": [
                                {
                                    "header": str(
                                        header_row.iloc[c]
                                    ).strip(),
                                    "header_format": header_format
                                }
                                for c in range(c0, c1 + 1)
                            ]
                        }
                    )


    except Exception as e:

        print(
            f"\nERROR writing report: {e}"
        )

        continue


    # --------------------------------------------------
    # CONSOLE OUTPUT
    # --------------------------------------------------

    partial_entries = len(
        df_latest
    )


    if progress_col in df_latest.columns:

        above_70 = len(
            df_latest[
                df_latest[
                    progress_col
                ] >= 70
            ]
        )

        below_69 = len(
            df_latest[
                df_latest[
                    progress_col
                ] <= 69
            ]
        )

    else:

        above_70 = 0
        below_69 = 0


    title = (
        f"Report: "
        f"{output_filename}"
    )


    print(
        f"\n{title}"
    )


    col1_width = 35
    col2_width = 10


    print(
        f"{'Metric':<{col1_width}}"
        f"{'Count':>{col2_width}}"
    )


    metrics = [
        (
            "Partial Entries",
            partial_entries
        ),
        (
            "Above 70%",
            above_70
        ),
        (
            "Below 69%",
            below_69
        ),
        (
            "New Partial Entries This Week",
            len(weekly_new)
        ),
        (
            "Latest Report",
            latest_filename
        ),
        (
            "Previous Report",
            os.path.basename(
                previous_file
            )
        )
    ]


    for metric, value in metrics:

        print(
            f"{metric:<{col1_width}}"
            f"{str(value):>{col2_width}}"
        )


print(
    "\nAll files processed."
)